name: ðŸ“Š Coverage
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/coverage.yml"
      - "modules/**"

jobs:
  coverage:
    name: ðŸ“Š Coverage
    runs-on: 'ubuntu-latest'
    steps:
      - name: â¤µï¸ Checkout Sources
        uses: actions/checkout@v2
      - name: ðŸ˜ Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
          ini-values: xdebug.mode=coverage
      - name: âœ”ï¸ Validate composer.lock
        run: composer validate --strict --no-interaction
      - name: ðŸ’¾ Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-8.1-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-8.1-composer-
      - name: ðŸ“¦ Install dependencies
        run: composer install --no-interaction --no-progress --no-scripts
      - name: ðŸ”‘ Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY_COVERAGE }}
          known_hosts: unnecessary
      - name: â¤µï¸ Checkout coverage repository
        run: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts && \
          git clone git@github.com:philly-framework/coverage.git tmp/coverage/html --depth=1
      - name: ðŸ“Š Run PHPUnit Coverage
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-html tmp/coverage/html
      - name: âž• Commit updated coverage report
        uses: EndBug/add-and-commit@v7
        with:
          cwd: './tmp/coverage/html'
          message: ${{ format('Update coverage report ({0}@{1})', 'philly-framework/base', github.sha) }}
          pull: NO-PULL
