name: üìä Coverage
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/coverage.yml"
      - "modules/**"

jobs:
  coverage:
    name: üìä Coverage
    runs-on: 'ubuntu-latest'
    steps:
      - name: ‚§µÔ∏è Checkout Sources
        uses: actions/checkout@v2
      - name: üêò Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
          ini-values: xdebug.mode=coverage
      - name: ‚úîÔ∏è Validate composer.lock
        run: composer validate --strict --no-interaction
      - name: üíæ Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-8.1-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-8.1-composer-
      - name: üì¶ Install dependencies
        run: composer install --no-interaction --no-progress --no-scripts
      - name: üîë Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY_COVERAGE }}
          known_hosts: unnecessary
      - name: ‚§µÔ∏è Checkout coverage repository
        run: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts && \
          git clone git@github.com:philly-framework/coverage.git tmp/coverage/html --depth=1 && \
          cd tmp/coverage/html && \
          find . -maxdepth 1 ! -name .git ! -name .nojekyll ! -name . -exec rm -rv {} \;
      - name: üìä Run PHPUnit Coverage
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-html tmp/coverage/html
      - name: ‚§¥Ô∏è Push updated coverage report
        uses: EndBug/add-and-commit@v7
        with:
          cwd: './tmp/coverage/html'
          message: ${{ format('{0} ({1}@{2})', github.event.commits[0].message, 'philly-framework/base', github.sha) }}
          pull: NO-PULL
