name: ðŸ“Š Coverage
on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: ðŸ“Š Coverage
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php-version: [ '8.1' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: â¤µï¸ Checkout Sources
        uses: actions/checkout@v2
      - name: ðŸ˜ Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: âœ”ï¸ Validate composer.lock
        run: composer validate --strict --no-interaction
      - name: ðŸ’¾ Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-version }}-composer-
      - name: ðŸ“¦ Install dependencies
        run: composer install --no-interaction --no-progress --no-scripts
      - name: â¤µï¸ Checkout coverage repository
        run: |
          ssh-keyscan github.com > /root/.ssh/known_hosts && \
          echo "${{ secrets.SPLITSH_COVERAGE_KEY }}" > /root/.ssh/github && \
          chmod 0600 /root/.ssh/github && \
          echo "Host github\n    Hostname github.com\n    IdentityFile /root/.ssh/github\n    User git" > /root/.ssh/config && \
          git clone git@github.com:philly-framework/coverage.git ./tmp/coverage/html --depth=1
      - name: ðŸ“Š Run PHPUnit Coverage
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-html tmp/coverage/html
      - name: âž• Commit updated coverage report
        run: |
          git add . && \
          git commit -m "Update coverage report" && \
          git push origin main
