name: ğŸ“Š Coverage
on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: ğŸ“Š Coverage
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php-version: [ '8.1' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: â¤µï¸ Checkout Sources
        uses: actions/checkout@v2
      - name: ğŸ˜ Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: âœ”ï¸ Validate composer.lock
        run: composer validate --strict --no-interaction
      - name: ğŸ’¾ Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-version }}-composer-
      - name: ğŸ“¦ Install dependencies
        run: composer install --no-interaction --no-progress --no-scripts
      - name: ğŸ“Š Run PHPUnit Coverage
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-html tmp/coverage/html
      - name: Disable jekyll
        run: touch tmp/coverage/html/.nojekyll
      - name: â© Run Splitsh
        uses: philly-framework/action-splitsh@master
        with:
          split: 'philly-framework/coverage'
          split_deploy_key: ${{ secrets.SPLITSH_COVERAGE_KEY }}
          split_prefix: 'tmp/coverage/html/'
          split_branch: main
