name: Unit Tests ğŸ§ª
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      php-version:
        required: true
        type: string
      prefer-source:
        required: false
        type: boolean
        default: false
      testsuite:
        required: false
        type: string
        default: 'default'

jobs:
  unit-test:
    name: Unit Tests ğŸ§ª
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout Sources ğŸ“
        uses: actions/checkout@v2
      - name: Setup PHP ${{ inputs.php-version }} ğŸ˜
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
      - name: Validate composer.lock âœ”ï¸
        run: composer validate --strict --no-interaction --no-ansi
      - name: Cache dependencies ğŸ’¾
        if: ${{ !inputs.prefer-source }}
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-${{ inputs.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.php-version }}-composer-
      - name: Install dependencies ğŸ“¦
        if: ${{ !inputs.prefer-source }}
        run: composer install --prefer-dist --no-progress --no-interaction --no-scripts --no-ansi
      - name: Install dependencies, ignoring lockfile ğŸ“¦
        if: ${{ inputs.prefer-source }}
        run: rm composer.lock && composer install --prefer-source --no-progress --no-interaction --no-scripts --no-ansi
      - name: Run PHPUnit ğŸ§ª
        run: vendor/bin/phpunit --testsuite ${{ inputs.testsuite }}
