name: Unit Tests ğŸ§ª
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      php-version:
        required: true
        type: string
      testsuite:
        required: true
        type: string

jobs:
  unit-test:
    name: Unit Tests ğŸ§ª
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout Sources ğŸ“
        uses: actions/checkout@v2
      - name: Setup PHP ${{ inputs.php-version }} ğŸ˜
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
      - name: Validate composer.lock âœ”ï¸
        run: composer validate --strict
      - name: Cache dependencies ğŸ’¾
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies ğŸ“¦
        run: composer install --prefer-dist --no-progress --no-interaction --no-suggest --no-scripts --no-ansi
      - name: Run PHPUnit ğŸ§ª
        run: vendor/bin/phpunit --testsuite ${{ inputs.testsuite }}
