name: ğŸ“‹ Update README Annotations
on:
  push:
    paths:
      - ".github/workflows/update-readme-annotations.yml"
      - "modules/**"
      - "bin/update-readme-annotations.php"

jobs:
  update-todos:
    name: ğŸ“‹ Update README Annotations
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Checkout Sources
        uses: actions/checkout@v2
      - name: â–¶ï¸ Run update-readme-annotations.php
        run: php bin/update-readme-annotations.php
      - name: â¤´ï¸ Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update README.md"
