name: ğŸ“‹ Update README Annotations
on:
  push:
    paths:
      - '.github/workflows/update-readme-annotations.yml'
      - 'development/**'
      - 'modules/**'
      - 'bin/update-readme-annotations'

jobs:
  update-todos:
    name: ğŸ“‹ Update README Annotations
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Checkout Sources
        uses: actions/checkout@v2
      - name: â–¶ï¸ Run update-readme-annotations
        run: php bin/update-readme-annotations
      - name: â¤´ï¸ Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update README.md"
